# special addreses (also check config/settings folder, there are more special addresses defined there)
special_addresses:
  short_address: "0x"

# testnet code_hashes
testnet_issuer_script_code_hash: "0xb59879b6ea6fff985223117fa499ce84f8cfb028c4ffdfdf5d3ec19e905a11ed"
testnet_token_class_script_code_hash: "0x095b8c0b4e51a45f953acd1fcd1e39489f2675b4bc94e7af27bb38958790e3fc"
testnet_token_script_code_hash: "0xb1837b5ad01a88558731953062d1f5cb547adf89ece01e8934a9f0aeed2d959f"
testnet_cota_registry_code_hash: "0x9302db6cc1344b81a5efee06962abcb40427ecfcbe69d471b01b2658ed948075"
testnet_cota_regular_code_hash: "0x89cd8003a0eaf8e65e0c31525b7d1d5c1becefd2ea75bb4cff87810ae37764d8"

# mainnet code_hashes
mainnet_issuer_script_code_hash: "0x24b04faf80ded836efc05247778eec4ec02548dab6e2012c0107374aa3f68b81"
mainnet_token_class_script_code_hash: "0xd51e6eaf48124c601f41abe173f1da550b4cbca9c6a166781906a287abbb3d9a"
mainnet_token_script_code_hash: "0x2b24f0d644ccbdd77bbf86b27c8cca02efa0ad051e447c212636d9ee7acaaec9"
mainnet_cota_registry_code_hash: "0x90ca618be6c15f5857d3cbd09f9f24ca6770af047ba9ee70989ec3b229419ac7"
mainnet_cota_regular_code_hash: "0x1122a4fb54697cf2e6e3a96c9d80fd398a936559b90954c6e88eb7ba0cf652df"

# nrc 721 output data headers
nrc_721_factory_output_data_header: "0x24ff5a9ab8c38d195ce2b4ea75ca8987"
nrc_721_token_output_data_header: "0x0ddeff3e8ee03cbf6a2c6920d05c381e"

# hash length of an attribute(especially which comes from bytea column),
# e.g. Block.uncle_block_hashes: "0x587f354162afd133b4a4f7a4b621d11e043c3c08b0af2801f1686b5403b14953", which has a length of 66 ( 2 + 64)
default_hash_length: "64"

# this prefix is '0x'
default_with_prefix_hash_length: "66"

# short hash length of an attribute,
# e.g. Block.proposals: ["0xd092cc2023", "0x8844c12abf", "0x0000000000", "0x0000000000"]
default_short_hash_length: "10"

# prefix string for hash, e.g. 0xa1b2c3d4...
default_hash_prefix: "0x"

# used to get lock info
secp_multisig_cell_type_hash: "0x5c5069eb0857efc65e1bca0c07df34c31663b3622fd3876c876320fc9634e2a8"

# used to determine cell type
dao_code_hash: "0x516be0333273bbe12a723f3be583c524f0b6089326f89c49fc61e24d1f56be21"
dao_type_hash: "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e"
sudt_cell_type_hash: "0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5"
sudt1_cell_type_hash: ''

# epoch reward
default_epoch_reward: "1_917_808_21917808"

# code hash for test only. TODO remove it?
initial_block_reward: "5_000_000_000_000"

# code hash for test only. TODO remove it?
code_hash: "0x973bdb373cbb1d752b4ac006e2bb5bdcb63431ed2b6e394b22721c8906a2ad72"
secp_cell_type_hash: "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
secp_multisig_cell_code_hash: "0xc1fb0ae6915d3d4eded3498aedf5faddd8c5f6bd8921e0f8bfabd5ebcbf259bc"

homepage_transactions_records_count: 15
homepage_block_records_count: 15
proposal_window: 10
