hosts:
  - "http://localhost:8114"

special_addresses:
  short_address: "0x"

testnet_issuer_script_code_hash: "0xb59879b6ea6fff985223117fa499ce84f8cfb028c4ffdfdf5d3ec19e905a11ed"
testnet_token_class_script_code_hash: "0x095b8c0b4e51a45f953acd1fcd1e39489f2675b4bc94e7af27bb38958790e3fc"
testnet_token_script_code_hash: "0xb1837b5ad01a88558731953062d1f5cb547adf89ece01e8934a9f0aeed2d959f"

mainnet_issuer_script_code_hash: "0x24b04faf80ded836efc05247778eec4ec02548dab6e2012c0107374aa3f68b81"
mainnet_token_class_script_code_hash: "0xd51e6eaf48124c601f41abe173f1da550b4cbca9c6a166781906a287abbb3d9a"
mainnet_token_script_code_hash: "0x2b24f0d644ccbdd77bbf86b27c8cca02efa0ad051e447c212636d9ee7acaaec9"

nrc_721_factory_output_data_header: "0x24ff5a9ab8c38d195ce2b4ea75ca8987"
nrc_721_token_output_data_header: "0x0ddeff3e8ee03cbf6a2c6920d05c381e"
